### ISSUE TITLE
Hello，could you send me the lecture notes or materials of the 'inference and informaiton'  Thank you very much! 2464437090@qq.com

### ISSUE THREAD

**Issue by wojiaobaixiaofei** [jpjanet/6.437Project#1]
Hello，could you send me the lecture notes or materials of the 'inference and informaiton' 
Thank you very much!
2464437090@qq.com

**Comment by jpjanet** [comment]
I won't distribute copyrighted material but you can always try the MIT open courseware website: https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-438-algorithms-for-inference-fall-2014/ for closely related material
